version: 2
jobs:
  build:
    docker:
      - image: docker:18.09.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: DOCKER_BUILDKIT=1 docker --config=./docker-config build -t asonawalla/unbake .
